@ECHO OFF
: Set the masm path
SET PROJECT=%CD%
SET PROJECTINC=%PROJECT%\include
SET PROJECTLIB=%PROJECT%\lib
SET PROJECTRES=%PROJECT%\res

SET MASMPATH=\Programs\Development\RCE\Assemblers\MASM
SET MASMBIN=%MASMPATH%\bin
SET MASMINC=%MASMPATH%\include
SET MASMLIB=%MASMPATH%\lib

%MASMBIN%\ml.exe /c /coff /I"%MASMINC%" /I"%PROJECTINC%" keylog.main.asm
IF %ERRORLEVEL% NEQ 0 GOTO ERROR_BUILD

%MASMBIN%\polink.exe /release /subsystem:windows /MAPINFO:EXPORTS /MAPINFO:FIXUPS /MAPINFO:LINES /VERBOSE /MACHINE:IX86 /out:"%PROJECT%\Bin\keylog.exe" /libpath:"%MASMLIB%" keylog.main.obj
IF %ERRORLEVEL% NEQ 0 GOTO ERROR_BUILD
    ECHO.
    ECHO COMPILATION OK.
    ECHO.
    GOTO FINISH

:ERROR_BUILD
    ECHO.
    ECHO AN ERROR HAS OCCURRED! NO COMPILATION HAS BEEN DONE.
    ECHO.
    GOTO FINISH

:FINISH
IF EXIST "%PROJECT%\*.obj" DEL "%PROJECT%\*.obj"
PAUSE>nul