;-----------------------------------------------------------------------
include windows.inc

include kernel32.inc
include user32.inc
include advapi32.inc
include	gdi32.inc
include msvcrt.inc
include masm32.inc

includelib user32.lib
includelib kernel32.lib
includelib advapi32.lib
includelib gdi32.lib
includelib msvcrt.lib
includelib masm32.lib
;-----------------------------------------------------------------------
